version: "3.8"

services:
  backend:
    image: career-track-backend
    environment:
      - DATABASE_URL=postgresql://careertrack_8r5f_user:kTwikho4TwUtxOITImJrffUb7PhzG8Od@dpg-cv0s6tqj1k6c73edit8g-a.oregon-postgres.render.com/careertrack_8r5f
      - SERVER_ADDRESS=:8080
      - LOG_LEVEL=INFO
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ml_service:
    build:
      context: ./ml
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  postgres_data:
