version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://careertrack_f38p_user:ib08LVqEQeueQCKGw60SiOHprXg0TQIG@dpg-cvc4okaj1k6c73e50ov0-a.oregon-postgres.render.com/careertrack_f38p
      - SERVER_ADDRESS=:8080
      - LOG_LEVEL=INFO
      - JWT_SECRET=alsdkjhf4lk5j4thy45lyyhl45jh
      - ML_SERVICE_URL=http://ml_service:5000
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ml_service:
    build:
      context: ./ml
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  postgres_data: