// Моковые данные для отладки и тестирования компонента заявок студента
export const mockApplications = [
  {
    id: 1,
    vacancyTitle: "Junior Frontend Developer",
    companyName: "Яндекс",
    location: "Москва",
    status: "На рассмотрении",
    appliedDate: "2023-05-15T10:30:00",
    coverLetter: "Я очень заинтересован в позиции Junior Frontend Developer в вашей компании. У меня есть опыт работы с React и JavaScript, и я быстро обучаюсь новым технологиям. Я уверен, что смогу внести свой вклад в вашу команду.",
  },
  {
    id: 2,
    vacancyTitle: "Стажер-разработчик",
    companyName: "ВКонтакте",
    location: "Санкт-Петербург",
    status: "Принято",
    appliedDate: "2023-04-20T14:45:00",
    responseDate: "2023-04-25T11:20:00",
    feedback: "Мы были впечатлены вашими навыками и энтузиазмом. Ждем вас в нашей команде!",
    coverLetter: "Мне было бы интересно начать свою карьеру в вашей компании. Я недавно закончил курс по веб-разработке и имею базовые знания HTML, CSS и JavaScript. Я готов много работать и быстро учиться.",
  },
  {
    id: 3,
    vacancyTitle: "Backend Developer",
    companyName: "Ozon",
    location: "Москва",
    status: "Отклонено",
    appliedDate: "2023-03-10T09:15:00",
    responseDate: "2023-03-17T16:30:00",
    feedback: "Спасибо за интерес к нашей компании. К сожалению, мы ищем кандидатов с большим опытом в бэкенд-разработке.",
    coverLetter: "У меня есть опыт работы с Java и Spring Framework. Я хотел бы присоединиться к вашей команде и развиваться как бэкенд-разработчик.",
  },
  {
    id: 4,
    vacancyTitle: "Fullstack Developer",
    companyName: "Avito",
    location: "Москва",
    status: "На рассмотрении",
    appliedDate: "2023-05-01T11:00:00",
    coverLetter: "Я имею опыт работы с React и Node.js, и я заинтересован в позиции Fullstack Developer в вашей компании. Я убежден, что мои навыки могут быть полезны для вашей команды.",
  },
  {
    id: 5,
    vacancyTitle: "Android Developer",
    companyName: "Mail.ru",
    location: "Москва",
    status: "Принято",
    appliedDate: "2023-02-05T10:00:00",
    responseDate: "2023-02-10T14:20:00",
    feedback: "Мы рады предложить вам позицию Android-разработчика в нашей компании. Ваш опыт работы с Kotlin и Android SDK впечатляет!",
    coverLetter: "Я разрабатываю мобильные приложения под Android более 2 лет. Мне нравится ваша компания, и я хотел бы стать частью вашей команды.",
  }
]; 